[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r api/requirements.txt",
  "cd frontend && npm install && npm run build"
]

[phases.build]
cmds = [
  "cp -r frontend/build api/static"
]

[start]
cmd = "python3 api/main.py"
