[phases.setup]
nixPkgs = ["python311", "nodejs_18"]
cmds = [
  "python3.11 -m ensurepip --upgrade"
]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && npm install && npm run build"
]

[phases.build]
cmds = [
  "cp -r frontend/build backend/static"
]

[start]
cmd = "python3 backend/app.py"
